### ISSUE TITLE
Text overflows the answer box

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#12]
In the example text from module 3, the text overflows the box. Ideally, when the text exceed the normal length of the answer boxes, the answer box would expand to fit all the text (and all other answer boxes would match the length so that they all were equal sizes), but this might not be simple to do

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328379932502734" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-39-11.png (https://nditech.aha.io/attachments/6662328379932502734/token/6c477f419b5071db822415e79143a90198baf2996b6e4f804a8a1ed99644439e.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-92

**Comment by blynchNDI** [comment]
Noticed this in the latest version of the code:
![screenshot from 2019-02-28 09-21-26](https://user-images.githubusercontent.com/31080607/53572906-53b4a380-3b3a-11e9-8cd7-bca484f11892.png)

**Comment by blynchNDI** [comment]
Here is another example:

![screenshot from 2019-02-28 11-02-15](https://user-images.githubusercontent.com/31080607/53579890-6e8e1480-3b48-11e9-8a25-844d05e19f22.png)

**Comment by jatin-narang** [comment]
This is done intentionally ,if text is more than container it becomes scrollable if container size is according to text size it will break uniformity and if we reduce the text size it will become less readable.
