### ISSUE TITLE
Answer boxes do not line up in the third module

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#13]
For the third game module, the answer boxes are not lined up on certain screens to varying degrees.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328378226934593" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-33-54.png (https://nditech.aha.io/attachments/6662328378226934593/token/1045462349acd727d69d72dc28393c4bad2711f0504a2738394967ff280f4a2b.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-91

**Comment by blynchNDI** [comment]
This appears to be fixed and no longer happening
