### ISSUE TITLE
Changing the score in the total score for a level does not change the completion screen

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#14]
When editing the json file to change the total score for a level, it changes the total score on the selection screen, but not on the completion screen. In the example below, I updated the total score to be 10. This changed the score to 10 for the selection scene as seen in the first screenshot, but it remained at 100 in two places on the completion screen as seen in the second screenshot.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328376481390020" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-35-04.png (https://nditech.aha.io/attachments/6662328376481390020/token/0afa148f11923d852b3fa73e618b6f7c7a1401680e2574c16482dd3ee5909485.download?size=original)

<span data-href="#aha_attachment_6662328376129767665" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-34-06.png (https://nditech.aha.io/attachments/6662328376129767665/token/4a30d2445270a5ef8733584d723eb207360b62904f562a9ac07274269838fe25.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-90

**Comment by blynchNDI** [comment]
Appears to be fixed
