### ISSUE TITLE
'Move to next level' button text does not fit within the button

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#15]
The text for the move to next level button (for example 'Move to Level 4') does not fit within the button, and cannot be seen without highlighting. The most obvious solution would be to make the button bigger.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328374142728229" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-04-57.png (https://nditech.aha.io/attachments/6662328374142728229/token/b469f896d0a13b7a520a4fbc25f6ae74cdfa9d472805784893b1dc57f6db64db.download?size=original)

<span data-href="#aha_attachment_6662328373894200056" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 12-04-59.png (https://nditech.aha.io/attachments/6662328373894200056/token/01e3cc2e0953942771bae8e6b9583607cd3220340ad16f69c405d9954a490fca.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-89

**Comment by blynchNDI** [comment]
Appears to be fixed
