### ISSUE TITLE
The score on the right of the profile page does not change to reflect game progress

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#16]
This is presumably linked to the issue with not being able to login, and so might not be a feature that is ready yet.

Aha! Link: https://nditech.aha.io/features/G4G-88

**Comment by jatin-narang** [comment]
Yes you are right, its a static page for now. This feature will come when login will be implemented.

**Comment by blynchNDI** [comment]
(Outside of scope)
