### ISSUE TITLE
Instruction page does not change / does not appear on the main page

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#17]
The instruction page should either be available on the homepage (since that's where people are most likely to need it) and/or it should be able to be changed based on what page the user is on (though if there are not too many instructions, they can all appear in the same box, and so it would not need to be changed).

Aha! Link: https://nditech.aha.io/features/G4G-87

**Comment by blynchNDI** [comment]
Instructions now appear on the home page. Looks good to me.
