### ISSUE TITLE
Phrase 'Need 20 in Level 1 to unlock.' should disappear after unlocking a level

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#18]
When a level is unlocked, the lock icon disappears and the color of the level is no longer faded. In addition, a phrase similar to 'Need 20 in Level 1 to unlock.' for each level that should also disappear.

Aha! Link: https://nditech.aha.io/features/G4G-86

**Comment by blynchNDI** [comment]
Appears to be fixed
