### ISSUE TITLE
No whitespace between the proceed button and the bottom of the screen

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#19]
The proceed button is touching the bottom of the screen. Ideally, there would be a slight gap between the button and the bottom of the screen.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328368148858714" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-38-40.png (https://nditech.aha.io/attachments/6662328368148858714/token/ff8637c7ced0890b0dc102157e19a00818f45f94ea22bda7c2f2c559b9e5bc27.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-85

**Comment by Harsh2777** [comment]
Hi, Can I work on it?

**Comment by blynchNDI** [comment]
Issue is fixed
