### ISSUE TITLE
Questions are showing up in a color that is not readable

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#21]
I am encountering an issue where questions are appearing with a color that is almost the same as the background color, making it not possible to read them unless you highlight them with the mouse.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328366650353196" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-23-58.png (https://nditech.aha.io/attachments/6662328366650353196/token/78f89abbd83b3339aaa93600f7fec46aed8f8b5e1a813aa8a6829c8219fb8069.download?size=original)

<span data-href="#aha_attachment_6662328366618523454" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-23-55.png (https://nditech.aha.io/attachments/6662328366618523454/token/6e6dc5bf7dab019242ad59a1569ce89099c7eeee5ddd672ab7bde64462c45bef.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-84

**Comment by blynchNDI** [comment]
Appears to be fixed
