### ISSUE TITLE
Proceed button should be more visible

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#22]
When selecting an answer for a question on the first level, the proceed button appears at the bottom of the screen below what was previously the bottom of the screen that you could scroll to. If you don't know that you are supposed scroll down further after selecting the answer, you might not be able to find the proceed button. Fixes would either be to always have the proceed button visible but not clickable until you select an answer (maybe make it gray before an answer is selected), or to have the submit button appear in a spot that would be more visible.

Aha! Link: https://nditech.aha.io/features/G4G-83

**Comment by blynchNDI** [comment]
Fixed - if you are scrolled down to the bottom of the page, the 'Proceed' button appears within your view
