### ISSUE TITLE
Proceed button hovers over answers

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#23]
After getting an answer wrong, the proceed button hovers at the bottom of the window even when scrolling up or down, so that it floats over other objects. It should instead stay at the bottom of the page below the correct answer.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6662328364977449397" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-26-09.png (https://nditech.aha.io/attachments/6662328364977449397/token/ab42e1620275cf8b10d241562a7beaca90bfc0fac61293d721eb21e42336eae7.download?size=original)

<span data-href="#aha_attachment_6662328364804281891" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-26-16.png (https://nditech.aha.io/attachments/6662328364804281891/token/83d2311d6e0b3f314f0497f7d70ebeb387f8e7021bd716f6ae64c4aa81b63469.download?size=original)

<span data-href="#aha_attachment_6662328363746193664" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-19 11-24-22.png (https://nditech.aha.io/attachments/6662328363746193664/token/99ef248343337dfbfd9e64c133ad939c7543f7418ba028d4750f73b5661ab29e.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-82

**Comment by blynchNDI** [comment]
This no longer appears to be happening
