### ISSUE TITLE
Unclear how to use login feature

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#24]
There is profile page with fields for email, name, and password, but there is no submit button, or a clear way to create an account, login to an account, or logout of an account. Also, there is a change password button, it is unclear how this works

Aha! Link: https://nditech.aha.io/features/G4G-81

**Comment by jatin-narang** [comment]
Login was not in the scope for this SOW, that profile page form was just to change the email/password for future scope. Profile page is a static page for now, it will make sense when backend will be integrated and login will be implemented.

**Comment by blynchNDI** [comment]
(Outside of scope)
