### ISSUE TITLE
Game allowed me to advance to the next level despite losing the previous one

### ISSUE THREAD

**Issue by stigsfoot** [nditech/demgames-debate#27]
Despite getting a score of 0 on the first level of the first module, I was able to advance to the second level despite getting every question wrong. After getting a winning score for the second level, I advanced to the third. After going back to the level screen, I then had access to levels 1 and 3, but not level 2, which should not be possible.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6663114423036159596" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-28 09-23-54.png (https://nditech.aha.io/attachments/6663114423036159596/token/4fcef0007310a0c125b6fd957c9e1640f0bf855abc95fdac63a554b51bacfcdd.download?size=original)

<span data-href="#aha_attachment_6663114423005208134" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Screenshot from 2019-02-28 09-25-12.png (https://nditech.aha.io/attachments/6663114423005208134/token/f6e7b2e15d4d86e7f1129ba7464219b6d5de324aab32878ea5596ec0fb8eca16.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://nditech.aha.io/features/G4G-94

**Comment by jatin-narang** [comment]
Raised a PR , pull it please and check
